core : 
    Database: App\Core\Database
    Session: App\Core\Session

service: 
    SecurityService: App\Service\SecurityService
    CompteService: App\Service\CompteService

repository:  
    UtilisateurRepository: App\Repository\UtilisateurRepository
    CompteRepository: App\Repository\CompteRepository
